# Generated by Django 2.0.5 on 2018-06-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='price',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='multi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='provider',
            name='update',
            field=models.DateField(null=True),
        ),
    ]
