# Generated by Django 2.0.5 on 2018-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
