# Generated by Django 2.0.5 on 2018-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summa_invoice',
            field=models.FloatField(default=0.0),
        ),
    ]
